spring:
 application:
  name: eureka-server
  
server: 
 port: 2001
 
eureka:
 server: 
 #自我保护状态
  enable-self-preservation: false
 instance:
  hostname: eureka01
 client:
  register-with-eureka: false
  fetch-register: false
  #添加eureok客户端依赖
  service-url: 
    defaultZone: http://eureka01:2001/eureka
  
